meta_product_name: "Ringr"
meta_title: "Ringr - Find players. Find a team. Play Sports Today."
meta_description: "Ringr seamlessly matches competitive sports teams with players at short notice in the UK. Works with football, hockey, netball, rugby, basketball, cricket."
meta_image: "cover.jpg"
